### ISSUE TITLE
TailwindCSS is overriding MenuItem hover color

### ISSUE THREAD

**Issue by vincentdchn** [formaat-design/reshaped#207]
Hi, first of all, thank you for all your work on the library. It's amazing.

**Describe the bug**
I encountered an issue while integrating TailwindCSS into my project. Specifically, importing Tailwind's `global.css` appears to interfere with the hover color functionality of the `<MenuItem />`  component. Despite following the documentation to configure TailwindCSS, the MenuItem's hover effect fails to produce the anticipated color change when global.css is active.

A clear example can be observed in the project's example setup, where the `<MenuItem/>` component is used with onClick properties in conjunction with TailwindCSS, as per the repository's reshaped use case (`./src/examples/tailwind-integration`).

**Environment (please complete the following information):**
- Browser: Chrome
- Version: 2.7.4

**Comment by blvdmitry** [comment]
Tried it in the Tailwind example and it seems like an issue with the css order. Tailwind css reset selectors override Reshaped styles because all of them have the same selector weight. So in case you put you css import before importing Reshaped in your root component - it should be sorted correctly. I will still include some additional selector priority for such cases until we can move to using `@layer`

**Comment by blvdmitry** [comment]
Added an additional override for the next release
