### ISSUE TITLE
Font Scaling Support?

### ISSUE THREAD

**Issue by petewins** [formaat-design/reshaped#221]
Hi, this is more of an inquiry than a feature request. I've been using reshaped and noticed all tokens including font sizes are pixel based. Browser zooming works since everything scales together but the browser's font size will be ignored

I was wondering about this design choice and if theres are any thing we need be wary of using only pixels

https://www.joshwcomeau.com/css/surprising-truth-about-pixels-and-accessibility/

**Comment by blvdmitry** [comment]
Hey, 100% something we would like to implement. We've looked into this before and since it would be a breaking change for the theme format, we've parked it for the major release this summer alongside the design updates based on what Figma will release at Figma config. Here is the ticket we use for tracking in our project board: https://github.com/orgs/formaat-design/projects/2?pane=issue&itemId=44288261
