### ISSUE TITLE
Button component settings reset when updating from v2.6 -> v2.11

### ISSUE THREAD

**Issue by b-graves** [formaat-design/reshaped#243]
<img width="423" alt="Screenshot 2024-04-15 at 16 43 38" src="https://github.com/formaat-design/reshaped/assets/56936483/138485b3-50bc-4b23-bffd-f66ccacea5cc">
v2.6
<img width="455" alt="Screenshot 2024-04-15 at 16 43 58" src="https://github.com/formaat-design/reshaped/assets/56936483/af08306f-c4f7-493b-98dd-7def0dd56af7">
v2.11

As you can see in [this video](https://www.loom.com/share/651fc46f927d4889b3804e7d4d705901?sid=23a8305e-8941-4762-afb1-01ac7884304c), I am having some issues updating from v2.6 to 2.11. When I update all my buttons are reset to default settings. As you can see the badge and all other components I can see in the files I've updated work okay, but the button gets stuck.

Are you able to help me with this please? Thanks!

**Comment by blvdmitry** [comment]
Hey, this seems to be related to one of the previous versions where we have switched to using an atom inside the button to reduce the amount of total variants required since it was above the Figma performance recommendation. Seems like Figma didn't handle this change properly when swapping libraries while it worked as intended within the library 🥲

We'll try to look into any possible way for fixing this but I can't guarantee a good outcome here due to how limited control over the component instances is. Do you have a lot of buttons to migrate in your product?

**Comment by b-graves** [comment]
Hi, thanks for this. Yes we have a lot of buttons so this is slightly alarming! Any help on how to solve this would be much appreciated!

Is this the first time you've come across this issue? I would have expected it to happen to everyone migrating buttons?

Is it because we skipped the intermediate versions and are jumping directly from 2.6 to 2.11?

**Comment by blvdmitry** [comment]
We'll investigate this more trying migrating the button from different versions to 2.11. It might take some time so not sure if this is blocking anything on your side. We might also decide to revert the button composition changes and release a patch to make sure it doesn't break the migration path for you

**Comment by blvdmitry** [comment]
Hey, so after trying a few approaches, probably the best way to mitigate this right now is for us to republish 2.11 with the old button structure. That should fix the library swapping issues. We don't plan to release any v2 minor versions right now and started working on v3 aiming for early July, slightly after the config. We'll re-apply the new structure again for v3 since it will contain other breaking changes too and we'll highlight all of them in our migration guidelines

**Comment by blvdmitry** [comment]
Updated the archive on the website. You can now find the old button structure file next to the original 2.11 release file in the Figma archive. Let me know if that works as expected for you 🙌

**Comment by b-graves** [comment]
Thanks for this! We are just not sure where to find the figma archive on the website?

Is it somewhere here?
<img width="539" alt="Screenshot 2024-04-22 at 13 22 41" src="https://github.com/formaat-design/reshaped/assets/56936483/965412f6-3827-4e5b-993c-6ff4a8cac870">

**Comment by blvdmitry** [comment]
It's inside the Download Figma library button, you'll find an additional file there with the old button variants setup

**Comment by b-graves** [comment]
Thanks! That works well, really appreciate your help with this. I don't really understand why this is only a problem for us? I would have expected it to be a problem for everyone migrating from old version? Going forwards will every new release contain this additional file and we just use that file instead of the main one?

**Comment by blvdmitry** [comment]
No, this happened to others as well but you were the first to report since not everyone updates the library so frequently or might have some of the components with custom implementation

**Comment by b-graves** [comment]
Hi @blvdmitry , we are looking to update to v3.0, but looking at the download I can't see the version with the old button mappings, do we still need this? Thanks!

**Comment by blvdmitry** [comment]
Hey, we currently don't have the old mapped version in v3 since it includes breaking changes and having the component split into 2 layers lets us stay within the Figma performance limitations for the amount of variants and add more variants in the future. We can potentially look into changing this behavior in the future depending on the new Figma features that let us reduce the amount of supported Figma variants or maybe dropping some of the existing ones (like `fullWidth`)
