### ISSUE TITLE
Add Accordion to Figma library

### ISSUE THREAD

**Issue by Gmack786** [formaat-design/reshaped#259]
I can't find the accordion asset in my reshaped library on figma, although I can see the documentation on the reshaped website.
Thanks!

**Comment by blvdmitry** [comment]
@Gmack786 considering that accordion is basically a rotating icon with a content placeholder (but can also have completely custom styles and custom triggers), would that still be useful for your case? Originally we've added it to utilities for that reason since it's increasing the design complexity with slot composition just for the sake of using the arrow icon

![Image](https://github.com/user-attachments/assets/9496301d-9c8f-4d3b-8b7e-a0d9176a83b3)
