### ISSUE TITLE
Accordion doc example is not correct - iconSize on the wrong place

### ISSUE THREAD

**Issue by vinizinmoraes** [formaat-design/reshaped#263]
**Describe the bug**
The docs give some options to increase the iconSize but the example doesn't work

| correct | doc version |
| ------- | ------ |
| ![image](https://github.com/formaat-design/reshaped/assets/830885/a46f4fe4-238d-4665-a260-0adc6e47443d) | ![image](https://github.com/formaat-design/reshaped/assets/830885/35deef19-0601-4350-90b2-58564fe4efab)|

Another question: is it possible to change the accordion icon without using a custom Accordion.Trigger?

**To Reproduce**
Using the accordion on the doc website https://reshaped.so/docs/utilities/accordion

**Comment by blvdmitry** [comment]
Hey, sorry @vinizinmoraes  for taking long to answer, preparing the next major release right now ✨
I've updated the documentation and we'll ship it along with the major. 

Regarding your question, we were thinking about it originally but decided not to provide it as a built-in functionality since that would likely mean that icon animation also has to change. What kind of icon are you looking for in your case? Is it completely different or something like a chevron pointing right?

**Comment by blvdmitry** [comment]
I'll close this ticket for now, feel free to reopen it in the future in case there are more details to address
