### ISSUE TITLE
Popover.Content position is not updated when Popover.Trigger position changes

### ISSUE THREAD

**Issue by mareksed** [formaat-design/reshaped#271]
**Describe the bug**
When position of Popover.Trigger is changed with `transform: translate()`, while popover content is open the position is not updated.

**To Reproduce**
https://codesandbox.io/p/sandbox/reshaped-toolbar-zvqqmw?file=%2Fsrc%2FApp.js%3A10%2C31

**Expected behavior**
Popover.Contents position is updated according to position change

**Screenshots**
![CleanShot 2024-07-05 at 17 49 12](https://github.com/formaat-design/reshaped/assets/138460915/eab8a690-741a-464b-9d88-5ce6d60c7e6d)

**Environment (please complete the following information):**
 - OS: MacOS
 - Browser Brave

**Comment by mareksed** [comment]
I looked into sources and sort of did quick fix, we can observe position change of the trigger

In flyoutReducer, I have changed
```javascript
		case "position":
			if (state.status !== "rendered" && state.status !== "visible") return state;
			return {
				...state,
				status: state.status === "visible" ? "visible" : "positioned",
				position: action.payload.position,
				styles: { ...defaultStyles, ...action.payload.styles },
			};
```

And in FlyoutControlled 
```javascript
	const { x, y } = triggerElRef.current?.getBoundingClientRect() ?? {};
	React.useEffect(() => {
		updatePosition();
	}, [x, y, updatePosition]);
```

**Comment by mareksed** [comment]
@blvdmitry I did look into handling position changes in more elegant way than my hacky snippet :), 
Found this blog and the section on Move Observations using IntersectionObserver looks really elegant https://samthor.au/2021/observing-dom/

**Comment by blvdmitry** [comment]
Nice, thanks for sharing. I will be looking into this after I'm done with the portal refs implementation 🙌

**Comment by blvdmitry** [comment]
Looking at all possible solutions, I ended up improving the screen and component resizing detection and exposing an `updatePosition` method in the `instanceRef`. It seems to be a better approach because it doesn't assume that position changes only based on the attributes updates and it doesn't implement any additional wrappers with intersection observer trigger simulation for all popovers. It also means you have better control over the behavior in general. 

One of the current downsides is that there are 2 refs involved, so button has to be wrapped with an addition element or there should be a way to merge multiple refs implemented on the product. This can be potentially solved on our side in the future with a new hook for merging refs or a way to pass the trigger ref from outside.

Here is a code snippet example:

```

export const foo = () => {
	const [x, setX] = React.useState(0);
	const [y, setY] = React.useState(0);
	const popoverRef = React.useRef<PopoverInstanceRef>();
	const triggerRef = React.useRef<HTMLSpanElement | null>(null);

	React.useEffect(() => {
		const observer = new MutationObserver(() => {
			ref.current?.updatePosition();
		});

		observer.observe(buttonRef.current!, { attributes: true, attributeFilter: ["style"] });
		return () => observer.disconnect();
	}, []);

	return (
		<>
			<View gap={2} direction="row">
				<Button onClick={() => setX(x + 10)}>x+</Button>
				<Button onClick={() => setX(x - 10)}>x-</Button>
				<Button onClick={() => setY(y + 10)}>y+</Button>
				<Button onClick={() => setY(y - 10)}>y-</Button>
			</View>

			<View align="center" justify="center" height="300px">
				<Popover active position="top" instanceRef={ref}>
					<Popover.Trigger>
						{(attributes) => (
							<span ref={buttonRef} style={{ transform: `translate(${x}px, ${y}px)` }}>
								<Button attributes={attributes} variant="solid">
									Root Topic
								</Button>
							</span>
						)}
					</Popover.Trigger>
					<Popover.Content>Content</Popover.Content>
				</Popover>
			</View>
		</>
	);
};
```

https://github.com/user-attachments/assets/c0901220-ac6c-4bc2-a5cc-521ddee95a0b

**Comment by blvdmitry** [comment]
Merging this today and going to release a patch supporting this, documentation will follow in the upcoming minor release
