### ISSUE TITLE
Dismissible, to handle closing of Flyouts automatically when used in Modal, Popover or DropdownMenu

### ISSUE THREAD

**Issue by mareksed** [formaat-design/reshaped#278]
**Is your feature request related to a problem? Please describe.**
@radix/primitives do have [Popover.Close](https://www.radix-ui.com/primitives/docs/components/popover) button which handles closing automatically.

**Describe the solution you'd like**
Dismissable to deactivate popover when used in FlyoutContext.

**Describe alternatives you've considered**
Current solutions requires user to create controlled component, and handle activate, deactivate manually.
Which is fine, but it would nice to reduce the need for a wrapper.

**Comment by blvdmitry** [comment]
Ready for the 3.1 release. Same as usual composition approach, using Dismissible internally and automatically calling Popover handleClose method + giving access to all other dismissible props. This seems to be a better API compared to just the close button, since you have control over alignment with the title of the popover (center vs top) and close button won't overlap with the popover text content like in other libraries

```
<Popover>
	<Popover.Trigger>
		{(attributes) => <Button attributes={attributes}>Open</Button>}
	</Popover.Trigger>
	<Popover.Content>
		<Popover.Dismissible closeAriaLabel="Close" align="center">
			Popover content
		</Popover.Dismissible>
	</Popover.Content>
</Popover>
```

![Image](https://github.com/user-attachments/assets/a4a57b9a-843d-4bba-af79-ba88c46ea3e3)

**Comment by mareksed** [comment]
@blvdmitry 
Interesting I would have instinctively made Dismissible context aware. So if it is used within a context that can be dismissed it would do so, so you would be able to compose one component in any Flyout, Modal etc... , without inflating their API surface.

But I see the value in "namespacing" it, user does not have to keep in mind if component is controlled/uncontrolled. Popover.Dismissible is uncontrolled variant of Dismissible essentialy.

Is there anything special about <Popover.Dismissible> at the moment what would happen if I drop it in other flyouts like DropdownMenu.  Is there also a DropdownMenu.Dismissible.

We do have dropdown menu looking like this.
![image](https://github.com/user-attachments/assets/4672c1aa-fae1-4dd1-9610-d6342c09bece)

**Comment by blvdmitry** [comment]
Yeah, there are always aliases for the uses to make the usage explicit instead of relying on the internal knowledge of the components. Same way there is Popover.Content and DropdownMenu.Content or Button.Aligner and MenuItem.Aligner.

Having dismissible automatically infer the parent context is possible but has its tradeoffs since that means it should check for those context and a tiny component without logic will start depending on flyouts and modals, as well as potentially might need to be extended in case products have their own contexts like this where dismissible should work automatically.
