### ISSUE TITLE
BorderColor not part of View responsive values

### ISSUE THREAD

**Issue by rauloaida** [formaat-design/reshaped#286]
Hi -- the UI I am implementing with Reshaped requires a responsive borderColor. My View should display a "neutral-faded" borderColor on large screens and no border on small screens. Running `reshaped v2.11.7` & `Next 14.14` 

<img width="560" alt="Screenshot 2024-08-01 at 5 47 25 PM" src="https://github.com/user-attachments/assets/4482f949-0166-417c-8f0b-a21cb2d87d94">

The `borderColor` is not listed as one of the responsive proprieties in the View docs. Do you have any suggestions for how I can make it responsive / turn it off for small screens?

 ```
<View gap={{ s: 6, m: 10 }} justify="center" direction={'row'} wrap={{ l: false }}>
        <View
          width={{ s: '100%', l: '100%' }}
          borderColor="neutral-faded"
          borderRadius="large"
          padding={{ s: 3, m: 10 }}
          maxWidth={{ l: STEP_MAX_WIDTH }}
        >
          {children}
 </View>```

**Comment by blvdmitry** [comment]
Hey, borderColor should be already responsive in the latest patches: https://www.npmjs.com/package/reshaped?activeTab=code

We're shipping those based on the requests we receive immediately but documentation usually gets released as a part of a minor release, with the changelog for all the patches since the last minor. So it's gonna be updated in 3.1 together with all other documentation changes once we're done with the implementation of the Spliiter utility :)

**Comment by rauloaida** [comment]
Nice! thank you for the quick response -- is there a timeline for the release of 3.1 + documentation updates?

**Comment by blvdmitry** [comment]
I'm hoping to wrap it up around next weekend, got to finish the component, make a few smaller improvements and write documentation for all changes. Meanwhile you can still install latest 3.0.x and get the responsive borders working
