### ISSUE TITLE
[FEATURE]: Controlled Dropdown Menu - onClose handler improvements

### ISSUE THREAD

**Issue by mareksed** [formaat-design/reshaped#288]
**Is your feature request related to a problem? Please describe.**
When using DropdownMenu in Controlled variant I do not know what caused the close event.
I need to handle it differently if user clicked on item or clicked outside.

```
const { deactivate, .... } = useToggle();

 <DropdownMenu
             onClose={() => deactivate()}
             ...
             ...
```

**Describe the solution you'd like**
```
const { deactivate, .... } = useToggle();

 <DropdownMenu
             onClose={
                 (source) => 
                    if (source === 'ITEM') deactivate()
                    if (source === 'CLICK_OUTSIDE') alert('reshaped is awesome')
             }
             ...
             ...
```

**Describe alternatives you've considered**
Wrapping every onClickHandler with this, will probably extend to have a custom DropdownMenu.Item
```
       const onMenuItemClick = React.useCallback(handler => {
        return args => {
            handler(args);
            deactivate();
        };
    }, [deactivate]);
```

**Additional context**
We are using reshaped on Canvas and click on Canvas is handling click outside and needs to trigger some logic if some Flyout is visible. But that is broken because the Flyout got already closed by  `onClose={deactivate}`

**Comment by blvdmitry** [comment]
Looking at the current implementation, there are 6 sources of what might close a flyout (note that it's wider than just the DropdownMenu since it's based on the same utility)
- on blur
- on mouse leave for hover triggerType
- on trigger click
- on pressing Tab in menus with arrow navigation
- on pressing Esc
- on clicking outside

Additionally menus close themselves on selecting an item and submenus close their parent menus.

So I'm thinking if I should just list all possible sources or if there are other ways to address this. Do I get it right that in this example, you basically try to prevent the default outside click close handler? Could it work if I provide an additional flag like `disableCloseOnOutsideClick` that would only prevent that handler from firing, allowing you to do it on the product side on canvas click?

**Comment by mareksed** [comment]
Hmm actually yes `disableCloseOnOutsideClick` would fix this usecase, without need of complex onClose handler.

**Comment by blvdmitry** [comment]
Added this flag for the upcoming release, planning to get done with it over the upcoming weekend
