### ISSUE TITLE
[BUG] Hotkey combinations using ALT

### ISSUE THREAD

**Issue by meisterdomi** [formaat-design/reshaped#320]
**Describe the bug**

Using a hotkey combination using `alt+...` isn't working in all cases. By relying on the `code` event property while **ALT** is pressed some keys like **SHIFT** won't work anymore because the `code` for it is either `ShiftRight` or `ShiftLeft`.

That being said, a combination of e.g. `alt+shift+n` works if
- `shift` then `alt` then `n` is pressed but not
- `alt` then `shift` then `n`

as in latter case `ShiftLeft` is being used internally

**To Reproduce**
Create an isolated reproduction on the CodeSandox:
https://codesandbox.io/p/sandbox/focused-mcnulty-llxfc9

**Expected behavior**

Key combinations including `alt+shift` should work independent from the pressed order.

**Screenshots**
<img width="661" alt="Screenshot 2024-09-18 at 16 20 55" src="https://github.com/user-attachments/assets/9c39a9d7-d083-4af8-a1f5-60d3156764e9">

**Environment (please complete the following information):**
OS: MacOs
Browser Chrome(latest)
Version [e.g. 22] 3.1.4

**Comment by blvdmitry** [comment]
Good point, it's getting caused by the part handling alt key combinations since in many cases it modifies e.key. It was only meant to happen for the letters and numbers but it was happening for other keys like shift too. I got the fix ready and releasing a patch, so it should only trigger for "shift" and not "shiftLeft"
