### ISSUE TITLE
useHotkey some modifiers get stuck after trigger

### ISSUE THREAD

**Issue by mareksed** [formaat-design/reshaped#338]
**Describe the bug**
After hitting modifier + a key, the modifier gets stuck.
For example hitting 

`mod + k`, you can hit only `k` and it will keep triggering the shortcut
`mod + f`, same behaviour

**To Reproduce**
https://codesandbox.io/p/sandbox/festive-hill-8jcgd3?file=%2Fsrc%2FApp.tsx%3A11%2C44

Basically what is happening in story book, if modifier has a "native" action this action is not blocked, 
so after this action is triggered, if you move your focus back to the story, the modifier will act as if it was pressed and you can just hit the key to trigger the shortcut.

So make sure that storybook panel with stories is open, because `mod + k` will move the focus there.

**Expected behavior**
When modifier is in hotkey are only triggered when modifiers are pressed
Shouldn't hotkeys block the default actions?

**Environment (please complete the following information):**
 - reshaped 3.2.1

**Comment by blvdmitry** [comment]
A part of the answer is that the default behavior is not prevented by default but you can pass a `preventDefault` option to enable that. I still see some cases when switching between the pressed combinations might not prevent it and I think I can also auto-prevent for more key combinations, like you suggested

**Comment by mareksed** [comment]
yes, I have totally missed it in docs.
Autoprevent would feel natural for our usecase where we have an app, but might not be for other use cases. 
Are you preventing some shortcuts by default?

**Comment by blvdmitry** [comment]
I'm currently not preventing any defaults to avoid unexpected results. Potentially I could've added preventDefault for the shortcuts with modifier keys but I can think of some use cases where it might be an issue and it will be harder to debug the problem because it's happening internally and not for all shortcuts. An example I like using for preventDefault the most is products triggering analytics based on shortcuts pressed and they might be expecting them to trigger a native behavior and have their function to be called as a side effect. 

What I see as a potential improvement for the case you're describing:
- Make sure that whenever focus leaves the window, all shortcuts get reset. This happens in your codesandbox example when focus moves to the search field and in storybook cmd + k when focus moves outside the preview iframe.
- I've also noticed that having multiple cmd shortcuts can be better. In my example I had cmd + k and cmd + v together. Triggerring cmd + k, releasing k and pressing v without releasing cmd doesn't trigger it. I need to check if that's the browser limitation or if there is actually a way around it.

**Comment by blvdmitry** [comment]
I think I won't open up a can of worms for the second one. it's an OS limitation with keyup events not firing while meta is pressed. It can be potentially solved with custom events but I'll wait for any reports of this behavior as I see a lot of potential risks in simulating native behavior with custom events. 

The reported bit is solved now and shipping in the next patch
