### ISSUE TITLE
useResponsiveClientValue arbitrary breakpoints

### ISSUE THREAD

**Issue by GelsonMR** [formaat-design/reshaped#341]
**Describe the bug**
I was trying to define responsive a `backgroundColor` for a `<View>` component, since the prop doesn't allow using the `{ s: 'white', m: 'black' }` patter, I had to use the `useResponsiveClientValue` hook, which should've solve the problem if it wasn't by the fact that the hook uses default breakpoint values not related to the theme that has been set.

The screenshot below shows that there are arbitrary breakpoints on the hook, shouldn't those values be taken from the `.json` theme file?

**Expected behavior**
It's expected that the breakpoints used as reference on the `useResponsiveClientValue` hook to match the breakpoints declared in the theme.

**Screenshots**
![Image](https://github.com/user-attachments/assets/c373273c-2587-46a0-9129-25bf923c7d00)

**Environment (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 3.2.0-canary.0

**Comment by blvdmitry** [comment]
Hey there, this issue has been addressed in the latest 3.2.0 release and now the hook is getting the viewport values from the theme. You will need to regenerate your theme after the update since I added breakpoints values to the theme output to handle this behavior.  Full changelog is available here: https://reshaped.so/docs/changelog

Hope this helps for your use case 🫰
