### ISSUE TITLE
Justify not working on Prod build (version 3.2.3)

### ISSUE THREAD

**Issue by vinizinmoraes** [formaat-design/reshaped#342]
**Describe the bug**
When I use `next build && next start` I get a different result from `next dev`. On the latest version (3.2.3). Looking on the images you will see where my problem is all justify css is not being correctly propagated.

**To Reproduce**
It can only be reproduced on a real env. Checking the difference between both commands

**Expected behavior**
It should be the same output

**Screenshots**
| Build prod version 3.2.3 | Local dev version 3.2.3 | Build prod version 3.2.0-canary.0 | 
| -------------------------- | -------------------------- | -------------------------- | 
| ![Image](https://github.com/user-attachments/assets/07c3f3f6-7c14-4742-921f-ec022b97d298) | ![Image](https://github.com/user-attachments/assets/e93acee2-6bfe-4842-a898-e1d5f9389117) | ![Image](https://github.com/user-attachments/assets/23d398ed-080b-483e-b15a-4d5140b03e9e) | 

**Environment (please complete the following information):**

**Additional context**
This is happening only on the new version

**Comment by blvdmitry** [comment]
Thanks for the report. This happened with the extraction of the justify styles into a separate reusable utility and lack of control over the css order across files. I've applied a temporary fix in 3.2.4 and I'll have this solved properly in 3.3.0 since it's including a more standardized approach of working with css utilities

**Comment by vinizinmoraes** [comment]
Thank you @blvdmitry do you know why this lack of control happens only when we build for prod and not on dev? On 3.3.0 this difference between build/local will be removed?

**Comment by blvdmitry** [comment]
The issue happens due to how css loaders usually work in webpack and differences between their dev and prod builds. I couldn't see it in Storybook as well because it only utilizes a dev build right now. With the next release, I plan to have these css utilties for common styles to be available externally as well and have a better handling for them using css layers and higher css specificity
