### ISSUE TITLE
Responsive properties are not working for Button component

### ISSUE THREAD

**Issue by mzbrandl** [formaat-design/reshaped#344]
**Describe the bug**
The [Responsive Properties](https://reshaped.so/docs/getting-started/react/core-concepts#responsive-properties) are not reacting to viewport changes. As in the codesandbox below I created a Button component `<Button size={{s: "large", m: "medium"}}>Hello</Button>`. When I change the screen size the button always stays at the "large" value.
Interestingly when i use ```const size = useResponsiveClientValue<ButtonProps["size"]>({s: "large", m: "medium"});``` as the size prop it behaves as expected.

**To Reproduce**
Create an isolated reproduction on the CodeSandox:
https://codesandbox.io/p/sandbox/little-architecture-jdzzx4

**Expected behavior**
Button changes size, as the viewport changes.

**Environment (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 130.0.6723.70

**Comment by blvdmitry** [comment]
Hi, I think this might be due to codesandbox not supporting custom postcss configs. You can try some of the framework examples here instead to check how responsive components work: https://github.com/formaat-design/reshaped/tree/main/examples

In case the same happens in your product, this is likely to a missing postcss.config.js file which we have described for each framework. For example, here is the next.js one: https://reshaped.so/docs/getting-started/integrations/next#add-a-postcss-config

Let me know if this helps or you still have issues

**Comment by mzbrandl** [comment]
Ah yes, it was the missing postcss configuration. I was able to resolve it, Thanks!
