### ISSUE TITLE
Autocomplete: Better support for different Options structure

### ISSUE THREAD

**Issue by ashwinibm** [formaat-design/reshaped#355]
**Is your feature request related to a problem? Please describe.**
I'd like to use the Autocomplete component with a list of `{id: resource_id, label: human_readable_name}` pairs. I would imagine this to be similar to `Select` components where the `value` is actually the ID and we can display the `human_readable_name` as name or label.
However, that does not seem possible with Autocomplete. Although I can display the human readable name as 
`<Autocomplete.Item key={id} value={id}>{label}<Autocomplete.Item>`, the `id` gets shown in the input box after selection.

The other problem with using value=id is filtering. So I'm forced to use the `label` everywhere like
`<Autocomplete.Item key={label} value={label}>{label}<Autocomplete.Item>`

But on form submit, I have to map the `label` back to `id` before posting to the API because ultimately, we use resource IDs to update. This feels awkward.

**Describe the solution you'd like**
Would be good to support a way to:
- have the `id` in the form field value
- but use the human readable `label/name` for filtering and displaying

Perhaps something similar to [this autocomplete component](https://mui.com/material-ui/react-autocomplete/l)

**Describe alternatives you've considered**
Reverse look up with label but not ideal cuz it can be brittle. 

**Additional context**
https://github.com/user-attachments/assets/51b870fb-a500-4ee1-8ae6-33310acaf121

**Comment by blvdmitry** [comment]
Hey, just got to this ticket and have been thinking about the potential solutions here. One thing that got me thinking is that Autocomplete is using an input for displaying the value and that should be the label. So in order to store and submit the id of the option – it should be either save to the `input type="hidden"` or just saved to a separate value. Both probably mean there is another local state handling the selected id value. 

Looking at the MUI implementation, I think they allow to work with custom array data and `getOptionLabel` will let you render the text field value from it, but it still doesn't save the id anywhere if I get it right.

So since you'll have to store the selected id anyways and since we're using components composition, would the following approach work for you? Assuming I'll add a way to pass custom data as a prop to the `Autocomplete.Item` which then will be available in the `onItemSelect` arguments:

```tsx
const options = [
  {
    id: 0,
    title: "Paul Farell",
  },
  {
    id: 1,
    title: "Esther Naomi",
  },
  {
    id: 2,
    title: "Whitney Raynolds",
  },
];

function Field() {
  const [value, setValue] = React.useState("");
  const [selectedItem, setSelectedItem] = React.useState(null);

  return (
    <>
      <Autocomplete
        name="people"
        placeholder="Pick assignee"
        value={value}
        onChange={(args) => {
          setValue(args.value);
        }}
        onItemSelect={(args) => {
          setSelectedItem(args.data);
          setValue("");
        }}
      >
        {options.map((option) => {
          return (
            <Autocomplete.Item
              key={option.title}
              value={option.title}
              data={option}
            >
              {option.title}
            </Autocomplete.Item>
          );
        })}
      </Autocomplete>
      <input type="hidden" value={selectedItem.id} />
    </>
  );
}
```

**Comment by ashwinibm** [comment]
Getting the selected ID back via `data` is helpful for sure. The slight additional management of the hidden input field feels like a reasonable and practical way to handle the form data part of it. Given that the autocomplete is an input field underneath..
This works!

**Comment by blvdmitry** [comment]
Shipping in the next minor
