### ISSUE TITLE
Next 13 App directory compatibility

### ISSUE THREAD

**Issue by mmailaender** [formaat-design/reshaped#89]
Currently, all Reshaped components needs to be included in a "use client" component.

It would be great, if the components would ensure that by their self. And if possible also SSR, e.g. maybe for <Reshaped>

https://beta.nextjs.org/docs/rendering/server-and-client-components#third-party-packages

**Comment by blvdmitry** [comment]
We actually track this in this ticket: https://blvworkspace.notion.site/React-server-components-in-Next-9bc550e3e2694df29ae9b9648bc9a124

One of them is something Next.js has to address, the other one we're still looking at since it comes from the RSC limitation of not working with the context. I assume that there is no tree-shaking enabled in the dev environment which means that whenever you import components from the package, React.createContext gets called in the Reshaped provider and requires you to add "use client" on the product side. One temporary workaround is to import components directly from "reshaped/components/[componentName]", which should only keep the relevant components imported in your server component.

**Comment by blvdmitry** [comment]
13.1 was just announced and maybe this feature can solve the issue: https://nextjs.org/blog/next-13-1#import-resolution-for-smaller-bundles

**Comment by blvdmitry** [comment]
@mmailaender I've made some progress on this. It now works without specifying use client in every file, but for some reason it also disabled tree-shaking and still ships the whole library to the client, so looking into finding a way to make that work. Much closer now though.

**Comment by blvdmitry** [comment]
I will track issue separately now since the original overarching issue was resolved and  it depends now on enabling sideEffects in the package.json which doesn't work the same for all frameworks in terms of css order. A possible solution for it would be using css layers so I've decided to look into the more detailed browser support guidelines based on what we support already and see if we can use layers already.

**Comment by NoSync** [comment]
@blvdmitry what's the current status of this? The Notion board above doesn't seem to be accessible.

**Comment by blvdmitry** [comment]
Hey, it should work in app directory without errors and there are a few things we're waiting for next to ship, like additional features for the barrel files optimisations to improve tree-shaking. However even if some parts of the library don't tree-shake in all the cases - Reshaped library size is much smaller than most of the UI libraries out there. 
Also we have fully migrated to the app directory on our documentation website, which is a good additional test coverage for us, since it renders all the components without any errors.

**Comment by NoSync** [comment]
@blvdmitry thank you for the explanation. yep, that board works but I couldn't find anything related to this issue, hence my question. All clear now.

**Comment by blvdmitry** [comment]
Also FYI we have now completely moved to the GitHub project in this repo :)
